[general]
import = [
  "~/.config/alacritty/font-size.toml",
  "~/.config/alacritty/key-bindings.toml"
] 

live_config_reload = true


[env]
TERM = "xterm-256color"

[terminal.shell]
# program = "fish"
program = "distrobox-host-exec"
args = ["bash", "-l"]

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98
dimensions.columns = 90
dimensions.lines = 30

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

[colors]

  draw_bold_text_with_bright_colors = true
  
  [colors.primary]
  background = '#1a1b26'
  foreground = '#a9b1d6'
  
  # Normal colors
  [colors.normal]
  black = '#32344a'
  red = '#f7768e'
  green = '#9ece6a'
  yellow = '#e0af68'
  blue = '#7aa2f7'
  magenta = '#ad8ee6'
  cyan = '#449dab'
  white = '#787c99'
  
  # Bright colors
  [colors.bright]
  black = '#444b6a'
  red = '#ff7a93'
  green = '#b9f27c'
  yellow = '#ff9e64'
  blue = '#7da6ff'
  magenta = '#bb9af7'
  cyan = '#0db9d7'
  white = '#acb0d0'
  
  [colors.selection]
  background = '#7aa2f7'

[scrolling]
history = 10000
multiplier = 4


[debug]
#render_timer          = false
#persistent_logging    = false
#log_level             = "Warn"
#renderer              = "None"
#print_events          = false
#highlight_damage      = false
#prefer_egl            = false
